server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/movies/v1/users/**
        - id: service-movie
          uri: lb://service-movie
          predicates:
            - Path=/movies/v1/movie/**