server:
  port: 9203
  servlet:
    context-path: /movies/v1
spring:
  boot:
    admin:
      client:
        url: http://localhost:9020
  application:
    name: service-user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/tallerpds2users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
